unquote
calyptia/plugin pull request #37
Opened 2023-08-25 20:33 UTC by nicolasparada

2023-08-26 04:16 UTC, nicolasparada commented
I need help, there is a `testate/Dockerfile` which runs fluent-bit with an output plugin and we mount a temporal file into `/fluent-bit/etc/output.txt` but the output plugin `file` is giving `Permission Denied` error on the file path `/fluent-bit/etc/output.txt`.

I don't know how to fix this.

2023-08-28 08:33 UTC, niedbalski requested changes
Minor fix required. Indeed it works on mac. I will review this a bit deeper

```
➜ plugin (main) ✔ go test -v ./...
?   	github.com/calyptia/plugin/input	[no test files]
?   	github.com/calyptia/plugin/metric	[no test files]
?   	github.com/calyptia/plugin/metric/cmetric	[no test files]
=== RUN   TestPlugin
--- PASS: TestPlugin (101.05s)
PASS
ok  	github.com/calyptia/plugin	102.122s
=== RUN   TestGetRecord
--- PASS: TestGetRecord (0.00s)
PASS
ok  	github.com/calyptia/plugin/output	(cached)
```

2023-08-28 08:33 UTC, niedbalski commented on testdata/Dockerfile
> +RUN rm -rf ./testdata/output.txt
Why is this required? I don't think it is.

2023-08-28 08:33 UTC, niedbalski commented on plugin_test.go
> +	f, err := os.Create(filepath.Join(t.TempDir(), "output.txt"))
What are you doing with this?

2023-08-28 09:24 UTC, niedbalski approved these changes
LGTM

2023-08-28 09:24 UTC, merged

2023-08-28 14:03 UTC, nicolasparada commented on plugin_test.go
> +		err := os.RemoveAll(f.Name())
This is not required since I was using `t.TempDir()` and that entire directory gets removed once the test finishes.